### PR TITLE
Format md files in precommit hook

### LINKED ISSUE #134: prettier precommit to format usecases
As suggested by @102 in #133

### PR DESCRIPTION
**Pull request by 102**
- [x] Check [CONTRIBUTING.md](https://github.com/jadjoubran/codetogo.io/blob/master/CONTRIBUTING.md)?

Closes #134

### CODE REVIEW

**Comment by jadjoubran** [comment]
Thanks! 🎉
any specific reason for the tabs width 4 and single quotes?
I think the use cases were 4 spaces before, but since we're using prettier, I'm thinking why not just keep the defaults
Curious to know what you think, and thanks again for your time!

**Comment by jadjoubran** [comment]
If you're on twitter, I'd love to give you a shoutout 😄 just tell me your handle

**Comment by 102** [comment]
@jadjoubran yeah, I've used 4 tabs & single quote just to make the smaller amount of changes in previous pull request as I can.

I'm @9z3 at twitter 😄

**Comment by jadjoubran** [comment]
alright makes sense, so I'll remove the custom settings and make another push
I still haven't fixed the build process properly, everytime I make a change, I have to build and push tons of changes in `build_production` which is committed
but now that I've migrated from gh-pages to netlify, I'll fix that soon

**Pull request merged**
