### PR TITLE
find the Index of an element in an Array 

### PR DESCRIPTION
**Pull request by politologu**
---
extends: _layouts.usecase
date: 2018-03-25
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex
reference: find the Index of an element in an Array 
related: Single-Character-from-a-String 
category: arrays
---

```javascript
var colors = ["red", "green", "blue"];
colors.indexOf("blue");
colors.indexOf("green");
colors.indexOf("red");
```

<pre class="output">2</pre>
<pre class="output">1</pre>
<pre class="output">0</pre>

### CODE REVIEW

**Comment by jadjoubran** [comment]
Thanks @politologu for this!
Unfortunately it seems you sent this PR from `gh-pages` which resulted in ~292 file changes
Can you please try again by simply going into this [url](https://github.com/jadjoubran/codetogo.io/tree/master/source/_usecases) and clicking on **Create new file** and then you could use the template that you used here
Thanks!

**Comment by politologu** [comment]
@jadjoubran thanks, its ok now?

**Comment by jadjoubran** [comment]
Sure!
I'm not sure what you mean?

**Comment by kakadiadarpan** [comment]
Hey @politologu, please check any other merged PR (check #116). You have to push only the related use case.

**Comment by politologu** [comment]
@kakadiadarpan thanks,  I submitted with success!

**Pull request closed without merging**
