### PR TITLE
find the Index of an element in an Array

### PR DESCRIPTION
**Pull request by politologu**
---
extends: _layouts.usecase
date: 2018-03-28
link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
reference: Array.indexOf
category: arrays
---

```javascript
const colors = ["red", "green", "blue"];
colors.indexOf("green");
```

<pre class="output">1</pre>

### CODE REVIEW

**Comment by kakadiadarpan** [comment]
Hey, @politologu please push all the requested changes in PR #124 to the same branch `patch-2`. No need to open a new PR for the review changes.

**Comment by jadjoubran** [comment]
agreed with @kakadiadarpan (for future PRs)
but for this time, no worries 😄 
it's great to see your first contribution, thanks for your time @politologu!
I will review it in a second

**Comment by jadjoubran** [comment]
Looks great! There's only 1 issue that I forgot to tell you about in the previous PR
Please rename the file from `find the Index of an element in an Array` to `find-index-of-element-in-array.md`

as the file type is markdown (`.md`) and the name of the usecase will be automatically generated from the file name( so the usecase will become: `How to find index of element in array in JavaScript`
Thanks!

**Comment by jadjoubran** [comment]
Closed in favor of #128

**Pull request closed without merging**
